### ISSUE TITLE
Missing Option "replace-input" 

### ISSUE THREAD

**Issue by AlexanderSch90** [mgodlewski/dockerfiles#10]
Hey is this true? Docker tells me: qpdf: unknown option --replace-input

Why this is not working? Thanks!

**Comment by mgodlewski** [comment]
The docker image was build on strech which come with version 6 of qpdf.
It's now upgraded to debian bullseye which come with version 10.1 of qpdf.

The  --replace-input option is known on the 10.1 version

fix by d9881302
