### ISSUE TITLE
HTTP 404 on pictos on v2.3.1.18083113

### ISSUE THREAD

**Issue by mathieupotier** [mgodlewski/dockerfiles#6]
It miss some images resources on that version ...
When you run this image, it seems that many resources are missing (or non resolvable).

Can you confirm that it's not a container issue ?

Regards

**Comment by mathieupotier** [comment]
`/Docs` are missing on my end...

**Comment by mathieupotier** [comment]
I'll prepare an update to stick on a given version for diacamma_asso, diacamma_syndic and lucterios_standard

**Comment by mgodlewski** [comment]
I reproduce this issue.
I guess your right : the problem come from lucterios.
